eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaServiceZone}
  instance:
    hostname: ${hostname}

server:
  port: ${appPort}

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${datasourceUrl}
    username: ${datasourceUsername}
    password: ${datasourcePassword}

jwt:
  secret: ${jwtSecret}
