server:
  port: ${appPort}

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${datasourceUrl}
    username: ${datasourceUsername}
    password: ${datasourcePassword}

jwt:
  secret: ${jwtSecret}
